In [1]:
import pandas as pd
import glob, os

In [2]:
path = r"C:\Users\tlles\Documents\DA15\Capstone\baseball_payroll_wins_capstone\data"

files = glob.glob(os.path.join(path, "attendance_*.csv"))

print(len(files), "files found:", [os.path.basename(f) for f in files])

10 files found: ['attendance_2015.csv', 'attendance_2016.csv', 'attendance_2017.csv', 'attendance_2018.csv', 'attendance_2019.csv', 'attendance_2021.csv', 'attendance_2022.csv', 'attendance_2023.csv', 'attendance_2024.csv', 'attendance_2025.csv']

In [7]:
dfs = []

for f in files:
    df = pd.read_csv(f)
    df.columns = [c.strip().lower() for c in df.columns]
    df["attendance"] = (
        df["attendance"].astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
        .replace({"":pd.NA})
        .astype("Int64")
    )
    dfs.append(df[["team","year","attendance"]])

attendace = pd.concat(dfs, ignore_index=True)
attendance.shape, attendance.head()

((300, 3),
                    team  year  attendance
 0  Arizona Diamondbacks  2015     2080145
 1        Atlanta Braves  2015     2001392
 2     Baltimore Orioles  2015     2281202
 3        Boston Red Sox  2015     2880694
 4          Chicago Cubs  2015     2919122)

In [6]:
attendance.head()

                   team  year  attendance
0  Arizona Diamondbacks  2015     2080145
1        Atlanta Braves  2015     2001392
2     Baltimore Orioles  2015     2281202
3        Boston Red Sox  2015     2880694
4          Chicago Cubs  2015     2919122

In [10]:
TEAM_FIXES = {
    "Los Angeles Angels of Anaheim": "Los Angeles Angels",
    "Cleveland Indians": "Cleveland Guardians",   # map to your canonical name
    "Florida Marlins": "Miami Marlins",
    "Tampa Bay Devil Rays": "Tampa Bay Rays",
}

attendance["team"] = attendance["team"].str.strip().replace(TEAM_FIXES)

In [11]:
attendance.head(30)

                     team  year  attendance
0    Arizona Diamondbacks  2015     2080145
1          Atlanta Braves  2015     2001392
2       Baltimore Orioles  2015     2281202
3          Boston Red Sox  2015     2880694
4            Chicago Cubs  2015     2919122
5       Chicago White Sox  2015     1755810
6         Cincinnati Reds  2015     2419506
7     Cleveland Guardians  2015     1388905
8        Colorado Rockies  2015     2506789
9          Detroit Tigers  2015     2726048
10         Houston Astros  2015     2153585
11     Kansas City Royals  2015     2708549
12     Los Angeles Angels  2015     3012765
13    Los Angeles Dodgers  2015     3764815
14          Miami Marlins  2015     1752235
15      Milwaukee Brewers  2015     2542558
16        Minnesota Twins  2015     2220054
17          New York Mets  2015     2569753
18       New York Yankees  2015     3193795
19      Oakland Athletics  2015     1768175
20  Philadelphia Phillies  2015     1831080
21     Pittsburgh Pirates  2015     2498596
22       San Diego Padres  2015     2459752
23       Seattle Mariners  2015     2193581
24   San Francisco Giants  2015     3375882
25    St. Louis Cardinals  2015     3520889
26         Tampa Bay Rays  2015     1287054
27          Texas Rangers  2015     2491875
28      Toronto Blue Jays  2015     2794891
29   Washington Nationals  2015     2619843

In [13]:
merged = pd.read_csv(r"C:\Users\tlles\Documents\DA15\Capstone\baseball_payroll_wins_capstone\data\mlb_payroll_wins_merge.csv")

In [14]:
merged.head()

,team_abbr,wins,year,games,team,win_pct,payroll,wins_per_$m
0,ARI,85,2000,162,Arizona Diamondbacks,0.524691,81027833,1.049022
1,ATL,95,2000,162,Atlanta Braves,0.586420,84537836,1.123757
2,BAL,74,2000,162,Baltimore Orioles,0.456790,81447435,0.908561
3,BOS,85,2000,162,Boston Red Sox,0.524691,77940333,1.090578
4,CHC,65,2000,162,Chicago Cubs,0.401235,60539333,1.073682

In [15]:
attendance["year"].value_counts()

year
2015    30
2016    30
2017    30
2018    30
2019    30
2021    30
2022    30
2023    30
2024    30
2025    30
Name: count, dtype: int64

In [16]:
final = merged.merge(attendance, on=["team","year"], how = "left")

In [17]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   team_abbr    780 non-null    object
 1   wins         780 non-null    int64
 2   year         780 non-null    int64
 3   games        780 non-null    int64
 4   team         780 non-null    object
 5   win_pct      780 non-null    float64
 6   payroll      780 non-null    int64
 7   wins_per_$m  780 non-null    float64
 8   attendance   299 non-null    Int64
dtypes: Int64(1), float64(2), int64(4), object(2)
memory usage: 55.7+ KB

In [18]:
attendance.nunique()

team           31
year           10
attendance    300
dtype: int64

In [20]:
attendance["team"].unique()

array(['Arizona Diamondbacks', 'Atlanta Braves', 'Baltimore Orioles',
       'Boston Red Sox', 'Chicago Cubs', 'Chicago White Sox',
       'Cincinnati Reds', 'Cleveland Guardians', 'Colorado Rockies',
       'Detroit Tigers', 'Houston Astros', 'Kansas City Royals',
       'Los Angeles Angels', 'Los Angeles Dodgers', 'Miami Marlins',
       'Milwaukee Brewers', 'Minnesota Twins', 'New York Mets',
       'New York Yankees', 'Oakland Athletics', 'Philadelphia Phillies',
       'Pittsburgh Pirates', 'San Diego Padres', 'Seattle Mariners',
       'San Francisco Giants', 'St. Louis Cardinals', 'Tampa Bay Rays',
       'Texas Rangers', 'Toronto Blue Jays', 'Washington Nationals',
       'Athletics'], dtype=object)

In [22]:
print(attendance.isna().sum())

team          0
year          0
attendance    0
dtype: int64

In [29]:
attendance["team"] = attendance["team"].replace({"Athletics": "Oakland Athletics"})

In [30]:
attendance.nunique()

team           30
year           10
attendance    300
dtype: int64

In [31]:
attendance["team"].unique()

array(['Arizona Diamondbacks', 'Atlanta Braves', 'Baltimore Orioles',
       'Boston Red Sox', 'Chicago Cubs', 'Chicago White Sox',
       'Cincinnati Reds', 'Cleveland Guardians', 'Colorado Rockies',
       'Detroit Tigers', 'Houston Astros', 'Kansas City Royals',
       'Los Angeles Angels', 'Los Angeles Dodgers', 'Miami Marlins',
       'Milwaukee Brewers', 'Minnesota Twins', 'New York Mets',
       'New York Yankees', 'Oakland Athletics', 'Philadelphia Phillies',
       'Pittsburgh Pirates', 'San Diego Padres', 'Seattle Mariners',
       'San Francisco Giants', 'St. Louis Cardinals', 'Tampa Bay Rays',
       'Texas Rangers', 'Toronto Blue Jays', 'Washington Nationals'],
      dtype=object)

In [32]:
final = merged.merge(attendance, on=['team', 'year'], how='left')

In [33]:
final.groupby('year')['attendance'].apply(lambda s: s.notna().sum())

year
2000     0
2001     0
2002     0
2003     0
2004     0
2005     0
2006     0
2007     0
2008     0
2009     0
2010     0
2011     0
2012     0
2013     0
2014     0
2015    30
2016    30
2017    30
2018    30
2019    30
2020     0
2021    30
2022    30
2023    30
2024    30
2025    30
Name: attendance, dtype: int64

In [34]:
final.to_csv("mlb_2000_2025_full.csv", index=False)

In [35]:
final.shape

(780, 9)

In [36]:
final.isna().sum()

team_abbr        0
wins             0
year             0
games            0
team             0
win_pct          0
payroll          0
wins_per_$m      0
attendance     480
dtype: int64